### ISSUE TITLE
cannot import name 'adam' from 'keras.optimizers'

### ISSUE THREAD

**Issue by HappyDay-design** [alexDS12/traffic-light-dqnagent#1]
Hello. Thank you for sharing your code.

When I ran the code, it had error "cannot import name 'adam' from 'keras.optimizers'

So I changed  "from keras.optimizers import Adam"
to :from tensorflow.keras.optimizers import Adam" and the model can ran well

**Comment by HappyDay-design** [comment]
But i do not fully understand your coding. So could you upload your thesis or some more instructions?
I think other people can more easily understand your model

**Comment by alexDS12** [comment]
Hello @TrinhTuanHung2021 ,

I'm deeply sorry for delaying a response on this!

The Keras module is a wrapper that uses TensorFlow API under the hood, I'm surprised you tested and it raised issues. I'll take a look and see if issue is still reproducible. Thanks for raising this!

As for your second question, my thesis is not in English unfortunately so I'll have to answer your questions here. At some point I'll have to document a little bit better about the model with theory from my thesis.

Could you please elaborate on your questions?
